class Config:
    def __init__(
        self,
        EPOCH=300,
        INPUT_CHANNELS=55,
        OUTPUT_CHANNELS=2,
        WEIGHT_DECAY=5e-4,
        SEED=42,
        LEARNING_RATE=0.01,
        HIDDEN_CHANNELS_1_GCN=32,
        HIDDEN_CHANNELS_1_GAT=32,
        HIDDEN_CHANNELS_1_TAGNN=32,
        HIDDEN_CHANNELS_2_GCN=16,
        HIDDEN_CHANNELS_2_GAT=16,
        HIDDEN_CHANNELS_2_TAGNN=16,
        DROPOUT=0.5,
        GAT_HEADS=2,
        SAMPLING_STRATEGY=0.7,
    ):
        self.EPOCH = EPOCH
        self.INPUT_CHANNELS = INPUT_CHANNELS
        self.OUTPUT_CHANNELS = OUTPUT_CHANNELS
        self.WEIGHT_DECAY = WEIGHT_DECAY
        self.SEED = SEED
        self.LEARNING_RATE = LEARNING_RATE

        self.HIDDEN_CHANNELS_1_GCN = HIDDEN_CHANNELS_1_GCN
        self.HIDDEN_CHANNELS_1_GAT = HIDDEN_CHANNELS_1_GAT
        self.HIDDEN_CHANNELS_1_TAGNN = HIDDEN_CHANNELS_1_TAGNN
        self.HIDDEN_CHANNELS_2_GCN = HIDDEN_CHANNELS_2_GCN
        self.HIDDEN_CHANNELS_2_GAT = HIDDEN_CHANNELS_2_GAT
        self.HIDDEN_CHANNELS_2_TAGNN = HIDDEN_CHANNELS_2_TAGNN

        self.DROPOUT = DROPOUT
        self.GAT_HEADS = GAT_HEADS
        self.SAMPLING_STRATEGY = SAMPLING_STRATEGY

    def __repr__(self) -> str:
        return f"Config(\nEPOCH={self.EPOCH},\nINPUT_CHANNELS={self.INPUT_CHANNELS},\nOUTPUT_CHANNELS={self.OUTPUT_CHANNELS},\nWEIGHT_DECAY={self.WEIGHT_DECAY},\nSEED={self.SEED},\nLEARNING_RATE={self.LEARNING_RATE},\nHIDDEN_CHANNELS_1_GCN={self.HIDDEN_CHANNELS_1_GCN},\nHIDDEN_CHANNELS_1_GAT={self.HIDDEN_CHANNELS_1_GAT},\nHIDDEN_CHANNELS_1_TAGNN={self.HIDDEN_CHANNELS_1_TAGNN},\nHIDDEN_CHANNELS_2_GCN={self.HIDDEN_CHANNELS_2_GCN},\nHIDDEN_CHANNELS_2_GAT={self.HIDDEN_CHANNELS_2_GAT},\nHIDDEN_CHANNELS_2_TAGNN={self.HIDDEN_CHANNELS_2_TAGNN},\nDROPOUT={self.DROPOUT},\nGAT_HEADS={self.GAT_HEADS},\nSAMPLING_STRATEGY={self.SAMPLING_STRATEGY}\n)"

    def __str__(self) -> str:
        return self.__repr__()
    
    def as_key(self) -> str: 
        return f"hc1={self.HIDDEN_CHANNELS_1_GCN},hc2={self.HIDDEN_CHANNELS_2_GCN},ss={self.SAMPLING_STRATEGY},heads={self.GAT_HEADS}"